apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadClientID }}
  name: "sa-{{ include "beachbreak-frontend.fullname" . }}"
  namespace: {{ .Release.Namespace }}