namespace ti8m.BeachBreak.Core.Domain.BuildingBlocks;

public abstract class AggregateRoot : Entity<Guid>
{
    private readonly List<IDomainEvent> uncommittedEvents = new();

    public long Version { get; set; }

    public IEnumerable<IDomainEvent> UncommittedEvents => this.uncommittedEvents;

    public void ClearUncommittedDomainEvents()
    {
        uncommittedEvents.Clear();
    }

    protected void RaiseEvent(IDomainEvent @event)
    {
        ApplyEvent(@event);

        Version++;
        uncommittedEvents.Add(@event);
    }

    /// <summary>
    /// AOT-safe event dispatcher method implemented by source generator.
    /// Each concrete aggregate will have this method generated with a type-safe switch expression.
    /// </summary>
    protected virtual void ApplyEvent(IDomainEvent @event)
    {
        throw new InvalidOperationException(
            $"ApplyEvent method not implemented for aggregate type {GetType().Name}. " +
            "This should be generated by AggregateEventDispatcherGenerator.");
    }
}
