//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ti8m.BeachBreak.QueryApi.Dto;
using System.Text.Json.Serialization;

namespace ti8m.BeachBreak.QueryApi.Serialization;

[JsonSerializable(typeof(AssessmentResponseDataDto))]
[JsonSerializable(typeof(AssignmentProgressDto))]
[JsonSerializable(typeof(CategoryDto))]
[JsonSerializable(typeof(CategoryPerformanceDto))]
[JsonSerializable(typeof(ConfigurableFeedbackDataDto))]
[JsonSerializable(typeof(EmployeeDashboardDto))]
[JsonSerializable(typeof(EmployeeDto))]
[JsonSerializable(typeof(EmployeeFeedbackSummaryDto))]
[JsonSerializable(typeof(EmployeePerformanceDto))]
[JsonSerializable(typeof(EvaluationRatingDto))]
[JsonSerializable(typeof(FeedbackQueryParams))]
[JsonSerializable(typeof(FeedbackRatingDto))]
[JsonSerializable(typeof(FeedbackTemplateDto))]
[JsonSerializable(typeof(GoalDataDto))]
[JsonSerializable(typeof(GoalResponseDataDto))]
[JsonSerializable(typeof(HRDashboardDto))]
[JsonSerializable(typeof(InReviewNoteDto))]
[JsonSerializable(typeof(ManagerDashboardDto))]
[JsonSerializable(typeof(ManagerOverviewDto))]
[JsonSerializable(typeof(OrganizationDto))]
[JsonSerializable(typeof(OrganizationMetricsDto))]
[JsonSerializable(typeof(PredecessorRatingDto))]
[JsonSerializable(typeof(QuestionnaireAssignmentDto))]
[JsonSerializable(typeof(QuestionnaireResponseDto))]
[JsonSerializable(typeof(QuestionnaireTemplateDto))]
[JsonSerializable(typeof(QuestionResponseDataDto))]
[JsonSerializable(typeof(QuestionResponseDto))]
[JsonSerializable(typeof(QuestionSectionDto))]
[JsonSerializable(typeof(ReviewChangeDto))]
[JsonSerializable(typeof(SectionResponseDto))]
[JsonSerializable(typeof(TeamAnalyticsDto))]
[JsonSerializable(typeof(TeamAssignmentDto))]
[JsonSerializable(typeof(TeamMemberMetricsDto))]
[JsonSerializable(typeof(TeamUrgentAssignmentDto))]
[JsonSerializable(typeof(TextResponseDataDto))]
[JsonSerializable(typeof(UrgentAssignmentDto))]
public partial class QueryApiJsonSerializerContext : JsonSerializerContext
{
}
