apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvsecrets-postgres
  namespace: {{ .Release.Namespace }}  # Change to your namespace
spec:
  provider: azure
  secretObjects:
    - secretName: postgres-secrets  # This creates a Kubernetes secret
      type: Opaque
      data:
        - objectName: POSTGRES-ADMIN-LOGIN
          key: postgres-admin-username
        - objectName: POSTGRES-ADMIN-PASSWORD
          key: postgres-admin-password
        - objectName: postgres-conn-string
          key: postgres-conn-string
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"  # Use this for managed identity
    userAssignedIdentityID: {{.Values.global.csiDriver.userAssignedIdentityID}}  # Add your managed identity client ID if using user-assigned identity
    keyvaultName: {{.Values.global.csiDriver.keyVaultName}}
    objects: |
      array:
        - |
          objectName: POSTGRES-ADMIN-LOGIN
          objectType: secret
          objectVersion: ""
        - |
          objectName: POSTGRES-ADMIN-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: postgres-conn-string
          objectType: secret
          objectVersion: ""
    tenantId: "7b8885d2-e886-46bd-abbc-5ee3e666ffc3"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvsecrets-app-reg
  namespace: {{ .Release.Namespace }}  # Change to your namespace
spec:
  provider: azure
  secretObjects:
    - secretName: app-reg-secrets  # This creates a Kubernetes secret
      type: Opaque
      data:
        - objectName: app-reg-client-id
          key: app-reg-client-id
        - objectName: app-reg-client-secret
          key: app-reg-client-secret
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"  # Use this for managed identity
    userAssignedIdentityID: {{.Values.global.csiDriver.userAssignedIdentityID}}  # Add your managed identity client ID if using user-assigned identity
    keyvaultName: {{.Values.global.csiDriver.keyVaultName}}
    objects: |
      array:
        - |
          objectName: app-reg-client-id
          objectType: secret
          objectVersion: ""
        - |
          objectName: app-reg-client-secret
          objectType: secret
          objectVersion: ""
    tenantId: "7b8885d2-e886-46bd-abbc-5ee3e666ffc3"