# Production environment values for QueryApi
replicaCount: 5

image:
  repository: acrbeachbreakproduction.azurecr.io/beachbreak/queryapi
  tag: "1.0.0"

ingress:
  hosts:
    - host: queryapi.beachbreak.ti8m.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: queryapi-tls
      hosts:
        - queryapi.beachbreak.ti8m.com
  annotations:
    nginx.ingress.kubernetes.io/rate-limit: "300"
    nginx.ingress.kubernetes.io/limit-rps: "150"

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 5
  maxReplicas: 25
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 3

keyVault:
  name: "kv-beachbreak-production"
