using ti8m.BeachBreak.Application.Command.Commands.EmployeeFeedbackCommands;

namespace ti8m.BeachBreak.CommandApi.Dto;

/// <summary>
/// DTO for cloning an existing feedback template.
/// Creates a new template as a copy with optional name prefix.
/// </summary>
public class CloneFeedbackTemplateDto
{
    /// <summary>
    /// ID for the new cloned template (generated by client).
    /// </summary>
    public Guid NewTemplateId { get; set; }

    /// <summary>
    /// Optional prefix for the cloned template name (e.g., "Copy of ").
    /// If not provided, defaults to "Copy of " in domain logic.
    /// </summary>
    public string? NamePrefix { get; set; }

    /// <summary>
    /// Converts DTO to domain command.
    /// </summary>
    public CloneFeedbackTemplateCommand ToCommand(Guid sourceTemplateId)
    {
        return new CloneFeedbackTemplateCommand(
            sourceTemplateId,
            NewTemplateId,
            NamePrefix ?? "Copy of ");
    }
}
