# Development environment values for Frontend
replicaCount: 1

image:
  repository: acrbeachbreakdev.azurecr.io/beachbreak/frontend
  tag: "latest"

ingress:
  hosts:
    - host: beachbreak-dev.ti8m.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: frontend-dev-tls
      hosts:
        - beachbreak-dev.ti8m.com

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: "Development"
  - name: ASPNETCORE_URLS
    value: "http://+:8080"
  - name: CommandApiUrl
    value: "http://commandapi.beachbreak.svc.cluster.local"
  - name: QueryApiUrl
    value: "http://queryapi.beachbreak.svc.cluster.local"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3

keyVault:
  name: "kv-beachbreak-dev"
