# Production environment values for Frontend
replicaCount: 3

image:
  repository: acrbeachbreakproduction.azurecr.io/beachbreak/frontend
  tag: "1.0.0"

ingress:
  hosts:
    - host: beachbreak.ti8m.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: frontend-tls
      hosts:
        - beachbreak.ti8m.com
  annotations:
    nginx.ingress.kubernetes.io/rate-limit: "200"
    nginx.ingress.kubernetes.io/limit-rps: "100"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: "Production"
  - name: ASPNETCORE_URLS
    value: "http://+:8080"
  - name: CommandApiUrl
    value: "http://commandapi.beachbreak.svc.cluster.local"
  - name: QueryApiUrl
    value: "http://queryapi.beachbreak.svc.cluster.local"

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 2

keyVault:
  name: "kv-beachbreak-production"
