apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "beachbreak-commandapi.fullname" . }}
  labels:
    {{- include "beachbreak-commandapi.labels" . | nindent 4 }}
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*"
    }
