//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ti8m.BeachBreak.CommandApi.Dto;
using System.Text.Json.Serialization;

namespace ti8m.BeachBreak.CommandApi.Serialization;

[JsonSerializable(typeof(AddCustomSectionsDto))]
[JsonSerializable(typeof(AddInReviewNoteDto))]
[JsonSerializable(typeof(AssignmentReminderDto))]
[JsonSerializable(typeof(BulkAssignmentReminderDto))]
[JsonSerializable(typeof(CategoryDto))]
[JsonSerializable(typeof(ChangeApplicationRoleDto))]
[JsonSerializable(typeof(CloneFeedbackTemplateDto))]
[JsonSerializable(typeof(CloneTemplateRequestDto))]
[JsonSerializable(typeof(CloneTemplateResponseDto))]
[JsonSerializable(typeof(ConfigurableFeedbackDataDto))]
[JsonSerializable(typeof(ConfirmReviewOutcomeDto))]
[JsonSerializable(typeof(CreateBulkAssignmentsDto))]
[JsonSerializable(typeof(CreateFeedbackTemplateDto))]
[JsonSerializable(typeof(EditAnswerDto))]
[JsonSerializable(typeof(EmployeeDto))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(ExtendAssignmentDueDateDto))]
[JsonSerializable(typeof(FeedbackProviderInfoDto))]
[JsonSerializable(typeof(FeedbackRatingDto))]
[JsonSerializable(typeof(FinalizeAsManagerDto))]
[JsonSerializable(typeof(FinishReviewMeetingDto))]
[JsonSerializable(typeof(InitializeAssignmentDto))]
[JsonSerializable(typeof(InsufficientPermissionsResponse))]
[JsonSerializable(typeof(LinkEmployeeFeedbackDto))]
[JsonSerializable(typeof(LinkPredecessorQuestionnaireDto))]
[JsonSerializable(typeof(QuestionnaireAssignmentDto))]
[JsonSerializable(typeof(QuestionnaireTemplateDto))]
[JsonSerializable(typeof(QuestionSectionDto))]
[JsonSerializable(typeof(RecordEmployeeFeedbackDto))]
[JsonSerializable(typeof(ReopenQuestionnaireDto))]
[JsonSerializable(typeof(SendReminderDto))]
[JsonSerializable(typeof(SignOffReviewDto))]
[JsonSerializable(typeof(StartProjectionReplayRequestDto))]
[JsonSerializable(typeof(SubmitQuestionnaireDto))]
[JsonSerializable(typeof(SyncDeletedOrganizationDto))]
[JsonSerializable(typeof(SyncOrganizationDto))]
[JsonSerializable(typeof(UnlinkEmployeeFeedbackDto))]
[JsonSerializable(typeof(UpdateEmployeeFeedbackDto))]
[JsonSerializable(typeof(UpdateFeedbackTemplateDto))]
[JsonSerializable(typeof(UpdateInReviewNoteDto))]
[JsonSerializable(typeof(WithdrawAssignmentDto))]
public partial class CommandApiJsonSerializerContext : JsonSerializerContext
{
}
